import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { setLicenseKey } from '@grapecity/wijmo';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

// setLicenseKey('GrapeCity,*.wijmo.com|*.grapecity.com,E255246575581915#B0hNLbhZmOiI7ckJye0ICbuFkI1pjIEJCLi4TPRhEdutidxpHSixmN5MXTwc4ZNVlY7o6UTZGRqhWbyQDanlUOKFlQCZTSxlTWMpWaFt6KIB5TlZHap96dqd6RLhXOTZjamBTezkjcwYVT986TulVNtBHc7gFaaBHeUhzRQJmQaJUc83yZGRmRmVjb55UWN3GaltycSJHOVVkdycjTrYGTFRnYElHMz44LiRnY9JENrYENuRVb6lUTzkGVxdjUBJndJlkeRRlVqFkbtJXSUF4TUp4SGVjdvh4R4JURu9GcOFTcm5kVP3CSBJUZQR5Uv4ke9dXQsdDVs9WZUNEdy46Ull5R7Y7V5NFcHF6RJdlcxljQz5EZoZVc6p4K4NGRJFlZzAVQMd7SQlmN5JUTqBVdldmcKlnb6okdrpWMQZXVN3kQYhkarU4dwVWbuhldXhkajhlVl3WTix4TWBjaUNEMwk4R9UDcZd5UM3Gdt3CaZ36TiojITJCLiATO6AjREljMiojIIJCL5UTO7kjN9kTM0IicfJye#4Xfd5nIJBjMSJiOiMkIsIibvl6cuVGd8VEIgQXZlh6U8VGbGBybtpWaXJiOi8kI1xSfiUTSOFlI0IyQiwiIu3Waz9WZ4hXRgAicldXZpZFdy3GclJFIv5mapdlI0IiTisHL3JyS7gDSiojIDJCLi86bpNnblRHeFBCI73mUpRHb55EIv5mapdlI0IiTisHL3JCNGZDRiojIDJCLi86bpNnblRHeFBCIQFETPBCIv5mapdlI0IiTisHL3JyMDBjQiojIDJCLiUmcvNEIv5mapdlI0IiTisHL3JSV8cTQiojIDJCLi86bpNnblRHeFBCI4JXYoNEbhl6YuFmbpZEIv5mapdlI0IiTis7W0ICZyBlIsIyMxYTM6ADI5AzNwgTMwIjI0ICdyNkIsISbvNmL9RXajVGchJ7ZuoCLt36Yu2Wbql6duoiI0IyctRkIsIibv9mbhJEIzlmcoNkI0ISYONkIsUWdyRnOiwmdFJCLiUTM9EDO5UzN5YDNyUTNyIiOiQWSiwSfiIjd9EDMyIiOiIXZcJ5L');

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
